[package]
name = "pf_sandbox_website"
version = "0.1.0"
authors = ["Lucas Kent <rubickent@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1"
rocket = { git = "https://github.com/rukai/Rocket", branch = "allow_creating_form" }
rocket_contrib = { git = "https://github.com/rukai/Rocket", branch = "allow_creating_form", features = ["handlebars_templates"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
git2 = "0.7"
chrono = { version = "0.4", features = ["serde"] }
